flowchart LR
	px --> qkq
	px --> A
	px --> rfg
	pv --> R
	pv --> A
	lnx --> A
	lnx --> A
	rfg --> gd
	rfg --> R
	rfg --> A
	qs --> A
	qs --> lnx
	qkq --> A
	qkq --> crn
	crn --> A
	crn --> R
	in --> px
	in --> qqz
	qqz --> qs
	qqz --> hdj
	qqz --> R
	gd --> R
	gd --> R
	hdj --> A
	hdj --> pv
